=== UCLM-ARCO/graf/question.dtd
<!-- DTD para la base de datos de preguntas  Ignacio Díez Arias -->

<!-- Un tema tiene una o mas preguntas (question) -->
<!ELEMENT qset (question+)>


<!-- una pregunta. Dentro puede contener un enunciado (text) o varias -->
<!-- partes (part). Después van los diferentes tipos de respuesta.-->
<!ELEMENT question (text?,part*,option*,freetext?,number?,item*)>
<!ATTLIST question id ID #REQUIRED>
 

<!-- enunciado de la pregunta -->
<!ELEMENT text (#PCDATA,complete*)>


<!-- opcion para preguntas de tipo test -->
<!ELEMENT option (freetext?,#PCDATA?)>
<!ATTLIST option correct (yes|no) "no">


<!-- para preguntas de respuesta libre -->
<!ELEMENT freetext (#PCDATA,correct)>
<!ATTLIST freetext
          rows CDATA ""
          readonly (yes|no) "yes">

<!-- respuesta correcta del freetext -->
<!ELEMENT correct (#PCDATA)>


<!-- para respuestas únicas (un número, una palabra...) -->
<!ELEMENT number (#PCDATA)>
<!ATTLIST number
          unit CDATA ""
          correct CDATA #REQUIRED>


<!-- para respuestas de elegir varias -->
<!ELEMENT item (freetext?,#PCDATA?)>
<!ATTLIST item correct (yes|no) "no">

<!-- para respuestas de rellena los espacios -->
<!ELEMENT complete (#PCDATA?)>
<!ATTLIST complete
            cols CDATA #REQUIRED
            correct CDATA #REQUIRED>


<!-- para preguntas con varias partes -->
<!ELEMENT part (text,option*,freetext?,number?,item*)>

=== UCLM-ARCO/graf/db/simpson/T1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- <!DOCTYPE qset SYSTEM "question.dtd"> -->

<qset>
  <question id="1">
	<text>¿Cuál es el nombre completo del jefe de policía de Springfield?</text>
	<option correct="no">Casey Wiggum</option>
	<option correct="no">Eliott Ness</option>
	<option correct="no">Charlie Wiggum</option>
	<option correct="yes">Clamcy Wiggum</option>
  </question>
  
  <question id="2">
	<part>
	  <text>
		¿En cuántas ocasiones ha intentado el actor secundario Bob
		acabar con Krusty?
	  </text>
	  <number units="veces" answer="3"/>
	</part>
	
	<part>
	  <text>¿Y cuántas veces se ha enfrentado a Bart?</text>
	  <number units="veces" correct="6"/>
	</part>
  </question>
	
  <question id="3">
	<text>¿Cómo consiguieron los Simpson a su perro?</text>
	<freetext rows="4">
	  <answer>
		En una carrera de galgos
	  </answer>
	</freetext>
  </question>

  <question id="4">
	<text>¿Cuáles de estos animales han pertenecido a la familia Simpson?</text>
	<item correct="no">Loro</item>
	<item correct="yes">Caballo</item>
	<item correct="no">Canguro</item>
	<item correct="yes">Pony</item>
	<item correct="no">Lobo</item>
	<item correct="yes">Gato</item>
	<item correct="yes">Elefante</item>
	<item correct="yes">Langosta</item>
  </question>

  <question id="5">
	<text>Completa los huecos</text>
	<completetext>
	  Homer <complete cols="3" correct="J."/> Simpson vive en
	  Springfield, en el <complete cols="5" correct="742"/> de
	  Evergreen Terrace. Tiene <number correct="3" units="hijos"/>:
	  Bart, de <complete cols="3" correct="10"/> años; Lisa, de
	  <complete cols="3" correct="8"/>, y <complete cols="10"
	  correct="Maggie"/>, de edad indeterminada.
	</completetext>
  </question>

  <question id="6">
	<text>¿Quién es el personaje de la figura?</text>
	<image src="./images/abuelo.gif">Figura 1</image>
	<option correct="no">Alcalde Quimby</option>
	<option correct="no">Dr. Julius Hibbert</option>
	<option correct="yes">Abe Simpson</option>
	<option correct="no">Reverendo Lovejoy</option>
  </question>
</qset>

=== UCLM-ARCO/graf/db/GNU/T2.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE qset SYSTEM "question.dtd">

<qset>
  <question id=1>
	<text>
	  ¿Cuál es el nombre completo del jefe de policía de
	  Springfield?
	</text>
	<option correct="no">Casey Wiggum</option>
	<option correct="no">Eliott Ness</option>
	<option correct="no">Charlie Wiggum</option>
	<option correct="yes">Clamcy Wiggum</option>
  </question>
  
  <question id=2>
	<part>
	  <text>
		¿En cuántas ocasiones ha intentado el actor secundario Bob
		acabar con Krusty?
	  </text>
	  <number units="veces" correct="3"/>
	</part>

	<part>
	  <text>¿Y cuántas veces se ha enfrentado a Bart?</text>
	  <number units="veces" correct="6"/>
	</part>
	
  <question id=3>
	<text>¿Cómo consiguieron los Simpson a su perro?</text>
	<freetext rows="4" />
  </question>

  <question id=4>
	<text>
	  ¿Cuáles de estos animales han pertenecido a la familia
	  Simpson?
	</text>
	<item correct="no">Loro</item>
	<item correct="yes">Caballo</item>
	<item correct="no">Canguro</item>
	<item correct="yes">Pony</item>
	<item correct="no">Lobo</item>
	<item correct="yes">Gato</item>
	<item correct="yes">Elefante</item>
	<item correct="yes">Langosta</item>
  </question>

  <question id=5>
	<text>
	  Homer <complete cols="3" correct="J."/> Simpson vive en
	  Springfield, en el <complete cols="5" correct="742"/> de
	  Evergreen Terrace. Tiene <complete cols="3" correct="3"/> hijos:
	  Bart, de <complete cols="3" correct="10"/> años; Lisa, de
	  <complete cols="3" correct="8"/>, y <complete cols="10"
	  correct="Maggie"/>, de edad indeterminada.
	</text>
  </question>
</qset>
